import os
import sys
import time
import chromadb
from chromadb.utils import embedding_functions
from llama_cpp import Llama  # Built for ultra-fast execution on standard CPUs

# --- PATH LAYOUT MATRIX ---
DATA_DIR = "data"
VECTOR_DB_DIR = os.path.join(DATA_DIR, "legal_ai_vector_db")
COLLECTION_NAME = "kenya_legal_documents"

# Points straight to your newly placed standalone 4-bit CPU model file
GGUF_MODEL_PATH = os.path.join("models", "llama-3-8b-instruct.Q4_K_M.gguf")

print("=" * 80)
print("⚖️ BOOTSTRAPPING SECURE LOCAL AI LEGAL INTERPRETER")
print("=" * 80)

# 1. Connect to your existing 5,232 local ChromaDB vector chunks
embedding_function = embedding_functions.DefaultEmbeddingFunction()
chroma_client = chromadb.PersistentClient(path=VECTOR_DB_DIR)
collection = chroma_client.get_collection(
    name=COLLECTION_NAME, 
    embedding_function=embedding_function
)
print(f"[✓] Local Vector DB Active: {collection.count()} legal chunks loaded.")

# 2. Initialize the quantized model into your machine's system RAM
print(f"[✓] Loading CPU-quantized model from: {GGUF_MODEL_PATH}")
if not os.path.exists(GGUF_MODEL_PATH):
    raise FileNotFoundError(f"❌ Error: Place your 'llama-3-8b-instruct.Q4_K_M.gguf' file inside the 'models/' folder first!")

llm = Llama(
    model_path=GGUF_MODEL_PATH,
    n_ctx=2048,
    n_threads=4  # Matches your local CPU layout core bounds for peak execution speed
)
print("[✓] Model successfully initialized into RAM memory maps.")
print("=" * 80)
print("SYSTEM READY. Type your question or type 'exit' to quit.\n")

# 3. INTERACTIVE TERMINAL LOOP
while True:
    try:
        question = input("\n👤 USER: ").strip()
        if not question:
            continue
        if question.lower() in ["exit", "quit"]:
            print("Closing local session. Goodbye!")
            break
            
        print("\n🔍 Searching local compliance databases...")
        # Query ChromaDB (Fast: <50ms)
        search_results = collection.query(query_texts=[question], n_results=3)
        retrieved_docs = search_results.get("documents", [[]])[0]
        retrieved_metas = search_results.get("metadatas", [[]])[0]
        
        if not retrieved_docs:
            context_str = "No specific background context available from internal database logs."
        else:
            context_str = ""
            for i, (doc, meta) in enumerate(zip(retrieved_docs, retrieved_metas)):
                source_id = meta.get("source_doc_id", "Unknown Gazette")
                context_str += f"[Source Document {source_id} (Chunk {i+1})]\n{doc}\n\n"
        
        # Injected your custom fine-tuned Llama-3 system instructions
        SYSTEM_PROMPT = (
            "You are a warm, highly empathetic Kenyan Legal Interpreter AI. Your purpose is to "
            "translate dense, intimidating legal jargon into clear, narrative-driven explanations "
            "that everyday citizens can immediately relate to and understand. Always rely heavily "
            "on the provided context to form your answers."
        )
        
        llama3_prompt_blueprint = """<|start_header_id|>system<|end_header_id|>

{}<|eot_id|><|start_header_id|>user<|end_header_id|>

CONTEXT SOURCE TEXTS:
{}

USER QUESTION:
{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

"""
        formatted_prompt = llama3_prompt_blueprint.format(SYSTEM_PROMPT, context_str, question)
        
        print("🤖 AI INTERPRETER: ", end="")
        sys.stdout.flush()
        
        # Execute instant 4-bit token streaming directly onto the terminal screen
        response_chunks = llm(
            formatted_prompt,
            max_tokens=512,
            temperature=0.1,
            top_p=0.9,
            stop=["<|eot_id|>", "user", "system"],
            stream=True  # Emits words as they are generated by the CPU
        )
        
        for chunk in response_chunks:
            token = chunk["choices"][0]["text"]
            if token:
                sys.stdout.write(token)
                sys.stdout.flush()
        print("\n" + "_"*80)
        
    except KeyboardInterrupt:
        print("\nExiting session safely.")
        break
